services:

  semta_server:
    build: .
    container_name: semta_server
    volumes:
      - ./Input:/usr/src/app/Input
      - ./Output:/usr/src/app/Output
      - ./Instance:/usr/src/app/Instance
    environment:
      FLASK_APP: Server.py
    ports:
      - "5000:5000"
    restart: unless-stopped
      
